#!/usr/bin/env python3
"""Generate the SDK's pinned offline host catalog from the verified Library."""
import argparse
import base64
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "services/library/src"))
from prim_library.library import Library
from prim_library.host_catalog import export_host_catalog

SOURCE_COMMIT = "50d829d5019ed2f2754dfb4fc11843bcd9d25cc9"


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    catalog = export_host_catalog(Library(), SOURCE_COMMIT)
    data = (json.dumps(catalog, ensure_ascii=True, indent=2) + "\n").encode()
    digest = hashlib.sha256(data).hexdigest()
    text = ("// Generated by tools/build_host_catalog.py; definitions only.\n"
            f'export const HOST_CATALOG_SHA256: string = "{digest}";\n'
            f'export const HOST_CATALOG_BASE64: string = "{base64.b64encode(data).decode()}";\n')
    path = ROOT / "sdk/typescript/src/profile-data.ts"
    if args.check:
        if not path.exists() or path.read_text() != text:
            p.error("Host catalog drift; run python tools/build_host_catalog.py")
    else:
        path.write_text(text)
    print(json.dumps({"profiles": len(catalog["kits"]), "sha256": digest, "source_commit": SOURCE_COMMIT}))


if __name__ == "__main__":
    main()
